# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$(document).ready ->
  $('#refresh_startdate').datepicker
    format: 'dd-mm-yyyy'
    weekStart: 1
  return

# ---
# generated by js2coffee 2.1.0
