# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$(document).ready ->
  $('#datepicker').datepicker
    dateFormat: 'yy-mm-dd'
    firstDay: 1
  return

# ---
# generated by js2coffee 2.1.0
